spec:
  replicas: 1
  template:
    spec:
      containers:
        -
          resources:
            requests:
              cpu: "0.2"
              memory: 128Mi
            limits:
              cpu: "1.0"
              memory: 512Mi
          env:
          - name: AMQP_SERVICE_NAME
            value: >-
              amqps://broker-amq-headless:5671?transport.trustStoreLocation=/data/broker.ts&transport.trustStorePassword=broker&transport.keyStoreLocation=/data/broker.ks&transport.keyStorePassword=broker&transport.verifyHost=false&jms.sendTimeout=5000
          - name: AMQP_USERNAME
            value: admin
          - name: AMQP_PASSWORD
            value: admin
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: JAVA_OPTS
            value: '-Djavax.net.debug=all -DUSER=admin -DPASSWORD=admin'